pizzaproject/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("", views.order_request, name="order_request"),
    path("orders/", views.order_table, name="order_table"),
]

pizzaproject/pizzaproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
]

pizzaproject/orders/models.py
from django.db import models

PIZZA_TYPES = (('Margherita', 'Margherita'), 
                ('Pepperoni', 'Pepperoni'), 
                ('Vegetarian', 'Vegetarian'),)
class Orderrequest(models.Model):
    pizzatype = models.CharField(max_length=100, choices=PIZZA_TYPES)
    commentorder = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.pizzatype} - {self.commentorder}"

    

pizzaproject/orders/forms.py
from django import forms
from .models import Orderrequest

class OrderForm(forms.ModelForm):

    class Meta:
        model = Orderrequest
        fields = ['pizzatype', 'commentorder']

pizzaproject/orders/views.py
from django.shortcuts import render, redirect

from .models import Orderrequest
from .forms import OrderForm

def order_request(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("orders:order_table")
    else:
        form = OrderForm()
    return render(request, 'orders/index.html', {'form': form})

def order_table(request):
    orders = Orderrequest.objects.all()
    return render(request, 'orders/pendings.html', {'orders': orders})

pizzaproject/orders/templates/orders/index.html
<h1>Pizza Order Form</h1>

<form action="{% url 'orders:order_request' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Order">
</form>
<ul>
    <li><a href="{% url 'orders:order_table'  %}">Check pendings Pizza orders</a></li>
</ul>

pizzaproject/orders/templates/orders/pendings.html
<table>
    <tr>
        <th>Pizza Type</th>
        <th>Comments</th>
    </tr>
    {% for order in orders %}
    <tr>
        <td>{{ order.pizzatype }}</td>
        <td>{{ order.commentorder }}</td>
    </tr>
    {% endfor %}
</table>
<ul>
    <li><a href="{% url 'orders:order_request'  %}">Create another Pizza order</a></li>
</ul>